---

  nxos_provider:
    username: "{{ un }}"
    password: "{{ pwd }}"
    transport: nxapi
    host: "{{ inventory_hostname }}"


  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: interface-vlan }
  - { feature: "nv overlay" }
  - { feature: vnseg_vlan }

  default_vrf_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }
  - { interface: Loopback0 }

  asn: 65001

  address_families:
  - { afi: ipv4, safi: unicast }
  #- { afi: l2vpn, safi: evpn }


  ipv4_unicast_neighbor:
   - { remote_as: 65001, neighbor: 10.10.10.1 }

  bgp_neighbors:
  - { remote_as: 65001, neighbor: 1.1.1.1, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 2.2.2.2, update_source: Loopback0 }



